### ISSUE TITLE
[Feat]feature/#61 알림 페이지 구현 (/home/alert) 

### ISSUE THREAD

**Issue by kimjj0** [Like-House/FE#64]
## 👀 어떤 기능을 추가할 것인가요?
> 알림 페이지 구현

## 🍀 기능을 추가하기 위해 어떤 작업이 진행될 것인가요?
> 기능을 추가하는 과정에서 진행될 작업에 대해 간략히 설명해주세요!
- [ ] 텝바로 전체, 채팅, 일정, 게시글 나누기
- [ ] 알림 컴포넌트 제작
- [ ] 알림 개수 나타내기

## ☕️ 어떤 브랜치에서 작업이 진행될까요?
> feature/#61

**Comment by hijjoy** [comment]
@kimjj0  원래는 브랜치가 #64가 아닐까요 ?!?
다음 개발때부터는 이슈생성 후에 옆에 써있는 #번호 로 브랜치 생성해주세요 !!
